'use client'
import { useEffect, useRef, useState } from 'react'
const stages=[
{id:'onboard',title:'Onboard',icon:'◎',text:'We start with a proper onboarding process: career goals, experience, target roles, locations, compensation and application preferences.'},
{id:'analyze',title:'Analyze',icon:'✦',text:'We screen your candidate profile and perform a structured SWOT analysis to identify strengths, gaps, opportunities and risks before applications begin.'},
{id:'discover',title:'Discover',icon:'⌕',text:'We search relevant openings across major countries and job sources, then prioritize roles that fit your agreed profile.'},
{id:'apply',title:'Apply',icon:'↗',text:'We tailor and submit relevant applications, track responses and move the pipeline toward interviews.'},
]
const countries=['🇺🇸 United States','🇨🇦 Canada','🇬🇧 United Kingdom','🇦🇺 Australia','🇩🇪 Germany','🇳🇱 Netherlands','🇮🇪 Ireland','🇸🇬 Singapore','🇦🇪 UAE','🇳🇿 New Zealand','🇫🇷 France','🇸🇪 Sweden','🇨🇭 Switzerland','🇮🇳 India']
const portals=['LinkedIn','Indeed','Glassdoor','Monster','ZipRecruiter','Dice','Wellfound','Hired','Naukri','Seek','Totaljobs','StepStone','JobStreet','Bayt','Jooble']
const companies=['Google','Microsoft','Amazon','Apple','Meta','IBM','Oracle','Cisco','Deloitte','Accenture','PwC','EY','KPMG','Capgemini','Infosys','TCS','Wipro','Siemens','SAP','ServiceNow']
export default function InteractiveHome(){
 const heroRef=useRef<HTMLDivElement>(null);const [active,setActive]=useState('onboard');const [scrolled,setScrolled]=useState(false);const slotsLeft=12
 useEffect(()=>{const f=()=>setScrolled(window.scrollY>30);window.addEventListener('scroll',f,{passive:true});const items=document.querySelectorAll('.reveal-on-scroll');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.12});items.forEach(i=>observer.observe(i));return()=>{window.removeEventListener('scroll',f);observer.disconnect()}},[])
 const tilt=(e:React.MouseEvent<HTMLDivElement>)=>{const el=heroRef.current;if(!el)return;const r=el.getBoundingClientRect();el.style.setProperty('--rx',`${((e.clientY-r.top)/r.height-.5)*-10}deg`);el.style.setProperty('--ry',`${((e.clientX-r.left)/r.width-.5)*10}deg`)}
 const reset=()=>{heroRef.current?.style.setProperty('--rx','0deg');heroRef.current?.style.setProperty('--ry','0deg')}
 return <>
 <div className={`progressbar ${scrolled?'visible':''}`}><span/></div><div className="cursor-glow"/>
 <section className="interactive-hero wrap reveal-on-scroll" onMouseMove={tilt} onMouseLeave={reset}><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-copy"><div className="live-pill"><span className="pulse"/> Managed career service · worldwide job search</div><h2 className="interactive-title">Don't just apply.<br/><span>Build a better search.</span></h2><p>JobApply is a managed job application service. We onboard you properly, analyze your candidate profile, perform a SWOT analysis and manage relevant applications across major countries and job portals.</p><div className="magnetic-actions"><a className="btn btn-dark magnetic" href="#start">Claim $499 launch price <b>→</b></a><a className="textlink" href="#service">See how we work ↓</a></div><div className="microproof"><span>✓</span> Minimum 3 months <span>✓</span> One-time payment <span>✓</span> Interview-focused process</div></div><div className="hero-scene" ref={heroRef} style={{'--rx':'0deg','--ry':'0deg'} as React.CSSProperties}><div className="scene-glow"/><div className="floating-chip chip-top"><span>PROFILE</span> SWOT analyzed</div><div className="floating-chip chip-bottom">Application pipeline <strong>Active</strong></div><div className="dashboard-pro"><div className="dash-head"><div><small>JOBAPPLY / MANAGED SEARCH</small><h3>Candidate pipeline</h3></div><div className="avatar">JA</div></div><div className="dash-stats"><div><b>47</b><span>Matched</span></div><div><b>18</b><span>Applied</span></div><div><b>4</b><span>Replies</span></div><div className="accent"><b>2</b><span>Interviews</span></div></div><div className="pipeline"><div className="pipeline-line"><span style={{width:'72%'}}/></div><div className="pipeline-labels"><span>Profile</span><span>Search</span><span>Apply</span><span>Interview</span></div></div><div className="live-job"><div className="company-logo">S</div><div className="job-meta"><b>Senior Security Engineer</b><span>Global employer · Remote</span><small>96% match</small></div><div className="job-state">New match</div></div><div className="live-job"><div className="company-logo">G</div><div className="job-meta"><b>GRC Consultant</b><span>Global employer · Hybrid</span><small>92% match</small></div><div className="job-state applied-state">Applied ✓</div></div></div></div></section>
 <section id="service" className="service-section reveal-on-scroll"><div className="wrap service-grid"><div><div className="section-kicker">WHY MINIMUM 3 MONTHS</div><h2>Good results need enough time.</h2><p className="service-copy">We require a minimum 3-month engagement because a serious job search is not a one-week campaign. The first stage is onboarding and profile analysis. Then we build the search strategy, identify suitable roles, submit quality applications, monitor employer responses and improve the approach based on market feedback. A longer runway gives the process enough time to generate a meaningful level of response.</p><p className="service-copy">JobApply is a hands-on managed career service. Our team handles the job-search workflow while you remain in control of your career decisions and employer conversations.</p></div><div className="swot">{[['STRENGTHS','Experience, certifications, achievements and differentiators we can position.'],['WEAKNESSES','Profile gaps, positioning issues and areas that may reduce response rates.'],['OPPORTUNITIES','Roles, industries, locations and markets where the profile can compete strongly.'],['THREATS','Competition, market conditions, skill gaps and application barriers.']].map(([t,p],i)=><div className="swot-card interactive-card" key={t}><b>{t}</b><p>{p}</p></div>)}</div></div></section>
 <section className="countries-section reveal-on-scroll"><div className="country-label">GLOBAL JOB SEARCH · MAJOR COUNTRIES</div><div className="country-marquee">{[...countries,...countries].map((c,i)=><div className="country" key={i}>{c}</div>)}</div></section>
 <section className="portal-section reveal-on-scroll"><div className="portal-title">We search across leading job portals</div><div className="portal-track">{[...portals,...portals].map((p,i)=><div className="portal" key={i}>{p}</div>)}</div></section>
 <section className="company-section reveal-on-scroll"><div className="company-title">TARGET EMPLOYERS ACROSS THE SEARCH</div><div className="company-track">{[...companies,...companies].map((c,i)=><div className="company" key={i}>{c}</div>)}</div></section>
 <section className="service-section seo-section reveal-on-scroll"><div className="wrap"><div className="section-kicker">JOB SEARCH SUPPORT WORLDWIDE</div><h2>Professional job search assistance for your next career move.</h2><p className="service-copy">Whether you are looking for technology jobs, cybersecurity jobs, software engineering jobs, finance jobs, consulting jobs, marketing jobs, engineering roles or senior professional opportunities, JobApply provides structured job search support from candidate profile analysis through application tracking and interview preparation.</p><p className="service-copy">Our international job search service can target opportunities in the United States, Canada, United Kingdom, Australia, Germany, Singapore, UAE, India and other markets. Depending on your preferences, we can focus on remote jobs, hybrid jobs, relocation opportunities, overseas careers and international employment opportunities.</p><p className="service-copy">If you need help finding a job, applying for jobs, improving your job search strategy, managing job applications, preparing for interviews or pursuing a career change, our managed service is designed to reduce the repetitive work and keep your search moving.</p></div></section>
 <section id="experience" className="experience wrap reveal-on-scroll"><div className="section-kicker">THE PROCESS</div><h2>From profile <span>to interview.</span></h2><p className="experience-lead">Click through the managed service journey.</p><div className="stage-tabs">{stages.map((s,i)=><button className={active===s.id?'active':''} onClick={()=>setActive(s.id)} key={s.id}><i>{s.icon}</i>{s.title}<span>0{i+1}</span></button>)}</div><div className="stage-panel">{stages.map((s,i)=>active===s.id&&<div className="stage-content stage-enter" key={s.id}><div className="stage-number">0{i+1}</div><div><h3>{s.title}</h3><p>{s.text}</p><div className="stage-progress"><span style={{width:`${(i+1)*25}%`}}/></div><small>STEP {i+1} OF 4</small></div><div className="stage-visual"><div className="radar"/><div className="stage-icon">{s.icon}</div></div></div>)}</div></section>
 <section className="scroll-story reveal-on-scroll"><div className="wrap story-grid"><div className="story-sticky"><div className="section-kicker">WHY JOBAPPLY</div><h2>Stop spending your best hours <span>on forms.</span></h2><p>We take the repetitive job-search workload off your plate while keeping the strategy focused on your profile and goals.</p><a className="btn btn-dark magnetic" href="#start">Start my search →</a></div><div className="story-cards">{[['01','Proper onboarding','We understand your profile before applications start.'],['02','SWOT analysis','We identify strengths, weaknesses, opportunities and threats affecting your search.'],['03','Global discovery','We can target relevant opportunities across major countries and leading job portals.'],['04','Managed applications','Relevant applications are tailored, submitted and tracked toward responses.']].map(([n,t,p])=><article className="interactive-card" key={n}><strong>{n}</strong><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="interactive-guarantee reveal-on-scroll"><div className="wrap guarantee-inner"><div><div className="section-kicker">THE LAUNCH OFFER</div><h2><s>$799</s> <span>$499</span></h2><p>Minimum 3 months. One payment. 15 total launch slots.</p></div><div className="slot-counter"><div className="slot-ring"><b>{slotsLeft}</b><small>left</small></div><div><strong>12 of 15 remaining</strong><p>3 launch slots are already filled. After all 15 slots, the price returns to $799.</p><div className="slot-bar"><span style={{width:'20%'}}/></div></div></div><a id="start" className="btn btn-dark magnetic" href="mailto:hello@jobapply.com?subject=Claim%20JobApply%20Launch%20Slot">Claim my slot →</a></div></section></>
}