import Link from 'next/link'

const posts = [
  ['how-to-find-a-job-faster','How to Find a Job Faster: A Practical Job Search Strategy','A practical framework for organizing your job search, choosing target roles, improving applications and increasing the quality of employer responses.','Job Search Strategy'],
  ['how-to-get-more-interviews','How to Get More Job Interviews: 10 Things That Actually Matter','Learn how profile positioning, role targeting, tailored applications and follow-up can improve your chances of reaching the interview stage.','Interview Tips'],
  ['done-for-you-job-application-services','Done-for-You Job Application Services: What to Look For','Understand what a professional job application service should include, from onboarding and candidate analysis to application tracking and interview preparation.','Career Support'],
  ['how-many-jobs-should-you-apply-to','How Many Jobs Should You Apply to Each Week?','Why application quality, role fit and consistency matter more than sending hundreds of generic applications.','Job Applications'],
  ['job-search-in-the-usa','How to Search for Jobs in the USA From Anywhere','A guide to targeting US employers, remote roles, relocation opportunities and international applications.','International Jobs'],
  ['job-search-in-the-uk','How to Find Jobs in the UK: A Guide for International Candidates','How to organize a UK job search, target suitable employers and prepare for applications from overseas.','International Jobs'],
  ['job-search-in-canada','How to Find a Job in Canada: Job Search Guide','Practical steps for targeting Canadian employers, remote opportunities and relocation-focused searches.','International Jobs'],
  ['resume-and-profile-analysis','Why Candidate Profile Analysis Matters Before Applying','How a structured review of skills, experience, achievements and gaps can improve job-search positioning.','Career Strategy'],
  ['swot-analysis-for-job-search','How to Do a SWOT Analysis for Your Career and Job Search','Use strengths, weaknesses, opportunities and threats to identify better roles and build a focused application strategy.','Career Strategy'],
  ['interview-preparation-guide','The Complete Job Interview Preparation Guide','A practical preparation framework covering research, storytelling, common questions, role-specific preparation and follow-up.','Interview Tips'],
] as const

export const metadata = { title: 'Job Search & Career Advice | JobApply Blog', description: 'Practical guides about job search strategy, job applications, interviews, international careers, candidate analysis and career growth.' }

export default function BlogPage(){return <main className="blog-page"><header className="wrap nav"><Link className="logo" href="/">JobApply<span /></Link><nav className="navlinks"><Link href="/">Home</Link><Link href="/blog">Career guides</Link></nav><Link className="btn btn-dark" href="/#start">Start your search →</Link></header><section className="blog-hero wrap"><div className="section-kicker">JOBAPPLY CAREER GUIDES</div><h1>Better job searches start with better information.</h1><p>Practical advice for finding jobs, improving applications, preparing for interviews and navigating international career opportunities.</p></section><section className="blog-grid wrap">{posts.map(([slug,title,excerpt,category],i)=><Link className="blog-card" href={`/blog/${slug}`} key={slug}><div className="blog-card-top"><span>{category}</span><b>{String(i+1).padStart(2,'0')}</b></div><h2>{title}</h2><p>{excerpt}</p><span className="read-more">Read guide →</span></Link>)}</section><footer className="site-footer"><div className="wrap footer-bottom"><span>© 2026 JobApply</span><span>Job search strategy · Career support · Interview preparation</span><Link href="/">Back to JobApply →</Link></div></footer></main>}
