import InteractiveHome from './components/InteractiveHome'

const faqs = [
  ['What exactly do I get?', 'You get a 3-month, done-for-you job search service covering candidate onboarding, profile analysis, target-role strategy, relevant job discovery, application tailoring, application submission, tracking, progress updates and interview preparation.'],
  ['Why is the minimum engagement 3 months?', 'A serious job search needs time. We begin with onboarding and candidate analysis, then build the search, submit relevant applications, monitor responses and refine the approach using market feedback. Three months gives the process enough runway to generate a meaningful level of employer response.'],
  ['Is the $499 a monthly fee?', 'No. The launch price is a one-time $499 payment covering the full 3-month service period. The regular price is $799. Only the first 10 launch slots are available at $499.'],
  ['How does the interview refund guarantee work?', 'If we complete the agreed 3-month service and you receive no qualifying interview invitation during that service period, you may request a refund of the service fee, subject to the eligibility and participation requirements in the Terms.'],
  ['Do you guarantee a job offer?', 'No. We do not guarantee employment, an offer, salary or a hiring decision. Employers control those decisions. Our guarantee is limited to the qualifying interview outcome described in the Terms.'],
  ['How many applications will you submit?', 'The exact volume depends on your target market, role seniority, availability of suitable openings and application requirements. We prioritize relevant, quality applications rather than indiscriminate submissions.'],
  ['Can I choose the roles and countries?', 'Yes. We align the search with your target roles, experience, preferred locations, compensation expectations and other agreed criteria. We can support international searches across major markets.'],
  ['Do you help after I get an interview?', 'Yes. Interview preparation is included so you can prepare for the role, understand likely questions and present your experience effectively.'],
]

export default function Home() {
  return <main>
    <header className="wrap nav"><a className="logo" href="#top">JobApply<span /></a><nav className="navlinks"><a href="#experience">Experience</a><a href="#offer">Pricing</a><a href="#faq">FAQ</a></nav><a className="btn btn-dark" href="#start">Claim $499 slot</a></header>
    <InteractiveHome />
    <section id="offer" className="section static-offer"><div className="wrap offer"><div><div className="eyebrow">LIMITED LAUNCH OFFER</div><h2>Three months of job-search momentum.</h2><p className="offer-copy">A focused service for professionals who are tired of spending evenings searching job boards and filling out the same forms. We handle the repetitive work while you stay in control of your career decisions.</p><div className="checklist">{['Candidate onboarding','Profile & SWOT analysis','Target-role strategy','Relevant job discovery','Tailored applications','Application submission','Application tracking','Interview preparation'].map(x=><div className="check" key={x}><i>✓</i>{x}</div>)}</div></div><div className="pricecard"><div className="limited"><strong>10 LAUNCH SLOTS</strong><span>Limited availability</span></div><div className="label">3-MONTH SERVICE</div><div className="oldprice">Regular price <s>$799</s></div><div className="price">$499 <span>one time</span></div><div className="save">SAVE $300 · FIRST 10 CLIENTS</div><p className="price-copy">We manage your job application process from candidate analysis and job search through interview preparation.</p><div className="guarantee"><strong>Interview refund guarantee</strong><br />If you complete the agreed service requirements and receive no qualifying interview invitation during the 3-month service period, your $499 service fee may be refunded, subject to the Terms.</div><a id="start" className="btn btn-dark" href="mailto:hello@jobapply.com?subject=Claim%20JobApply%20Launch%20Slot">Claim my $499 slot →</a><div className="fine center">No recurring payment · 10 launch slots only</div></div></div></section>
    <section id="faq" className="section faq-section"><div className="wrap"><div className="sectionhead"><h2>Questions, answered.</h2><p>Everything you need to know before handing over the job-search workload.</p></div><div className="faqgrid">{faqs.map(([q,a])=><details className="faq" key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    <section className="wrap cta"><div className="ctabox"><div className="ctaeyebrow">ONLY 10 LAUNCH SLOTS</div><h2>Get the first 10-client price before it is gone.</h2><p><s>$799</s> regular price. <strong>$499</strong> one time for the first 10 clients, covering 3 months of managed job search support.</p><div className="actions center-actions"><a className="btn btn-dark" href="#start">Claim $499 slot →</a></div></div></section>
    <footer className="site-footer">
      <div className="wrap footer-main">
        <div className="footer-brand"><a className="footer-logo" href="#top">JobApply<span /></a><p>A managed, done-for-you job application service built to take the repetitive work out of your search and move you toward interviews.</p><div className="footer-badge">MANAGED CAREER SERVICE</div></div>
        <div className="footer-col"><h4>Explore</h4><a href="#experience">How it works</a><a href="#service">Our process</a><a href="#offer">Pricing</a><a href="#faq">FAQ</a></div>
        <div className="footer-col"><h4>Service</h4><a href="#start">Claim a launch slot</a><a href="#experience">Interview preparation</a><a href="#service">Candidate analysis</a><a href="#service">Global job search</a></div>
        <div className="footer-col"><h4>Legal</h4><a href="/terms">Terms & Conditions</a><a href="/privacy">Privacy Policy</a><a href="mailto:hello@jobapply.com">Contact us</a></div>
      </div>
      <div className="wrap footer-bottom"><span>© 2026 JobApply. All rights reserved.</span><span>3-month minimum · $499 launch offer · First 10 clients</span><span>Refund terms apply · No job offer is guaranteed.</span></div>
    </footer>
  </main>
}
